# Generated by Django 2.2.7 on 2019-11-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='exclude_tags',
            field=models.ManyToManyField(blank=True, related_name='exclude_tags', to='videos.Tag'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_tags',
            field=models.ManyToManyField(blank=True, related_name='favorite_tags', to='videos.Tag'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_videos',
            field=models.ManyToManyField(blank=True, to='videos.Video'),
        ),
    ]
