# Generated by Django 2.2.7 on 2019-12-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
