# Generated by Django 2.2.7 on 2019-12-23 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20191223_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount',
            new_name='percentage',
        ),
    ]
