# Generated by Django 2.2.7 on 2019-12-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20191223_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='percentage',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
